# Generated by Django 4.2 on 2023-04-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('subscribers', models.IntegerField(default=0, null=True)),
                ('link', models.TextField(default=None)),
                ('imgUrl', models.TextField(default=None)),
            ],
            options={
                'db_table': 'Youtuber',
            },
        ),
    ]
